food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [  
    
    #/food/
    path("", views.index, name = "index"),
    
    #/food/1
    path('<int:item_id>/', views.detail,name='detail'),
    path("item", views.item, name = "item"),
    
    #add items
    path('add', views.create_item, name='create_item'),
    
    #edit items
    path('update/<int:id>/', views.update_item, name='update_item'),
  
]

myfoodsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("food/", include("food.urls")),
    path("admin/", admin.site.urls),
   
]

food/models.py
from email.policy import default
from django.db import models

# Create your models here.

class Item(models.Model):
    
    def __str__(self):
     return self.item_name

    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image= models.CharField(max_length=500,default="https://cdn.dribbble.com/users/1012566/screenshots/4187820/media/985748436085f06bb2bd63686ff491a5.jpg?resize=400x300&vertical=center")

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item    
        fields = ['item_name', 'item_d esc', 'item_price', 'item_image']

food/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm


# Create your views here.
def index(request):
   item_list = Item.objects.all()
   
   context ={
       'item_list': item_list,
       }
   return render(request, 'food/index.html', context)

def item(request):
    return HttpResponse("This is an item view")


def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context ={
        'item':item,
        }
    return render(request, 'food/detail.html', context)

def create_item(request):
    form = ItemForm(request.POST or None)
    
    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html', {'form':form}),

def update_item(request,id):
    item=Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    
    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html' ,{'form':form, 'item':item}),

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <title> Document </title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand"> FoodApp</a>

        <div class="navbar">
            <a class="nav-item" href="{% url 'food:create_item' %}">Add Item</a>
            <a class="nav-item" href="#">Delete Item</a>
            <a class="nav-item" href="#">View Item</a>
        </div>

    </nav>
    {% block body%}
    {% endblock %}
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html'%}

{% block body %}
<div class= "container">
    <div class="row">
    <div class=" ="col-md-6">
        <img height="300px" src="{{item.item_image}}"   class="card" />
        </div>


    <div class="col-md-6">
        <h1>{{ item.item_name }}</h1>
        <h2>{{ item.item_desc }}</h2>
        <h3>${{ item.item_price }}</h3>
    </div>
</div>
    </div>
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

</head>
<body>


    {% block body %}

    {% for item in item_list %}
    <div class="row">
         <div class="col-md-4 offset-mr-1">
             <img class="card" height="150px" src="{{ item.item_image }}"/>
             

         </div>
         <div class="col-md-6">
             <h3>{{ item.item_name}}</h3>
             <h5>{{item.item_desc}}</h5>
             <h6>${{item.item_price}}</h6>

         </div>
         <div class="col-md-2">
             <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
        </div>
    </div>


    {% endfor %}
    {% endblock %}

    This is the old code


    <ul>
        <li>

            <a href=" "> {{ item.id }} -- {{ item.item_name }}</a>
        </li>
    </ul>
  
</body>
</html> 

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}

<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Save</button>
</form>
{% endblock %}